"use client";
import { useState } from "react";
import { Sparkles, TrendingUp, TrendingDown } from "lucide-react";

const catStats = [
  {name:"Work",pct:83,done:10,total:12,color:"bg-blue-500"},{name:"Health",pct:12,done:1,total:8,color:"bg-emerald-500"},
  {name:"Home",pct:50,done:2,total:4,color:"bg-amber-500"},{name:"Loan",pct:50,done:2,total:4,color:"bg-red-500"},
  {name:"Friends",pct:50,done:1,total:2,color:"bg-purple-500"},{name:"Family",pct:67,done:2,total:3,color:"bg-pink-500"},
  {name:"Lifestyle",pct:67,done:2,total:3,color:"bg-teal-500"},
];
const insights = [
  {icon:"💼",title:"Work Efficiency",value:"83%",change:"+15%",positive:true,desc:"Completed 10 of 12 work tasks ahead of deadlines."},
  {icon:"💪",title:"Health Completion",value:"12%",change:"-28%",positive:false,desc:"Only 1 of 8 health tasks done. Missed 3 weeks in a row."},
  {icon:"🏦",title:"Loan Tasks",value:"50%",change:"–",positive:null,desc:"EMI paid on time. Car refinance and credit card pending."},
  {icon:"🔁",title:"Reschedule Rate",value:"31%",change:"+8%",positive:false,desc:"Rescheduled 5 tasks — 4 were health and home items."},
];
const suggestions = [
  {icon:"⏰",text:"Set a hard 6:30 AM alarm for gym Mon–Fri. You completed Monday's jog — build on that."},
  {icon:"📅",text:"Move 3 loan tasks from backlog to Tuesday & Thursday. Those days are free."},
  {icon:"🏠",text:"Block Saturday morning for home tasks. Last Saturday was completely free."},
  {icon:"🎯",text:"You have 24 backlog items. Run a 20-min grooming session on Sunday."},
];
const total=catStats.reduce((a,c)=>a+c.total,0), doneTot=catStats.reduce((a,c)=>a+c.done,0), rate=Math.round(doneTot/total*100);

export default function SummaryPage() {
  return (
    <div className="min-h-screen bg-stone-50">
      {/* Mobile header */}
      <div className="lg:hidden px-4 pt-4 pb-2">
        <p className="text-xs text-stone-400 mb-1">Week of Apr 14–20 · AI Generated</p>
        <div className="flex items-center gap-2">
          <h1 className="text-xl font-bold text-stone-900">Weekly Summary</h1>
          <span className="flex items-center gap-1 text-xs font-semibold px-2 py-0.5 rounded-full bg-orange-50 text-orange-700"><Sparkles className="w-3 h-3"/>AI</span>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 lg:px-8 py-4 lg:py-8">
        <div className="hidden lg:block mb-6">
          <p className="text-xs text-stone-400 mb-1">Week of Apr 14–20, 2026 · Generated by AI</p>
          <div className="flex items-center gap-2.5">
            <h1 className="text-2xl font-bold text-stone-900 tracking-tight">Weekly Summary</h1>
            <span className="flex items-center gap-1 text-xs font-semibold px-2.5 py-1 rounded-full bg-orange-50 text-orange-700"><Sparkles className="w-3 h-3"/>AI Powered</span>
          </div>
        </div>

        {/* Score ring */}
        <div className="bg-white border border-stone-200 rounded-2xl p-4 lg:p-6 mb-4 lg:mb-5 shadow-sm">
          <div className="flex items-center gap-4 lg:gap-6">
            <div className="relative w-20 h-20 lg:w-24 lg:h-24 shrink-0">
              <svg viewBox="0 0 36 36" className="w-full h-full -rotate-90">
                <circle cx="18" cy="18" r="15.9" fill="none" stroke="#F5F5F4" strokeWidth="3.5"/>
                <circle cx="18" cy="18" r="15.9" fill="none" stroke="#F97316" strokeWidth="3.5" strokeDasharray={`${rate} ${100-rate}`} strokeLinecap="round"/>
              </svg>
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <span className="text-lg lg:text-xl font-bold text-stone-900">{rate}%</span>
                <span className="text-[9px] lg:text-[10px] text-stone-400">done</span>
              </div>
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="text-sm lg:text-base font-semibold text-stone-900 mb-1">Solid on work, but health needs attention 💪</h2>
              <p className="text-xs lg:text-sm text-stone-500 leading-relaxed mb-3 hidden lg:block">Completed {doneTot} of {total} tasks this week. Work was excellent — health remains your weakest category for 3 weeks.</p>
              <div className="flex items-center gap-4 lg:gap-6">
                {[{l:"Completed",v:doneTot,c:"text-emerald-600"},{l:"Missed",v:total-doneTot,c:"text-red-500"},{l:"Rescheduled",v:5,c:"text-amber-600"}].map(s=>(
                  <div key={s.l}><p className={`text-lg lg:text-xl font-bold ${s.c}`}>{s.v}</p><p className="text-[10px] lg:text-xs text-stone-400">{s.l}</p></div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Insights */}
        <h2 className="text-sm lg:text-base font-semibold text-stone-900 mb-3">Key Insights</h2>
        <div className="grid grid-cols-2 gap-3 mb-4 lg:mb-5">
          {insights.map(ins=>(
            <div key={ins.title} className="bg-white border border-stone-200 rounded-xl p-3 lg:p-4 shadow-sm">
              <div className="flex items-start justify-between gap-2 mb-2">
                <span className="text-xl lg:text-2xl">{ins.icon}</span>
                <div className="text-right">
                  <p className="text-lg lg:text-xl font-bold text-stone-900">{ins.value}</p>
                  {ins.change!=="–"&&<p className={`text-xs font-medium flex items-center gap-0.5 justify-end ${ins.positive?"text-emerald-600":"text-red-500"}`}>
                    {ins.positive?<TrendingUp className="w-3 h-3"/>:<TrendingDown className="w-3 h-3"/>}{ins.change}
                  </p>}
                </div>
              </div>
              <p className="text-xs font-semibold text-stone-700 mb-1">{ins.title}</p>
              <p className="text-[11px] lg:text-xs text-stone-500 leading-relaxed">{ins.desc}</p>
            </div>
          ))}
        </div>

        {/* Category breakdown */}
        <h2 className="text-sm lg:text-base font-semibold text-stone-900 mb-3">Category Breakdown</h2>
        <div className="bg-white border border-stone-200 rounded-2xl p-4 lg:p-5 mb-4 lg:mb-5 shadow-sm space-y-3">
          {catStats.map(c=>(
            <div key={c.name}>
              <div className="flex items-center justify-between mb-1.5">
                <p className="text-xs lg:text-sm font-medium text-stone-700">{c.name}</p>
                <p className="text-xs text-stone-400">{c.done}/{c.total} · {c.pct}%</p>
              </div>
              <div className="h-1.5 rounded-full bg-stone-100 overflow-hidden"><div className={`h-full rounded-full ${c.color}`} style={{width:`${c.pct}%`}}/></div>
            </div>
          ))}
        </div>

        {/* Suggestions */}
        <h2 className="text-sm lg:text-base font-semibold text-stone-900 mb-3">Suggestions for Next Week</h2>
        <div className="space-y-2.5 pb-8">
          {suggestions.map((s,i)=>(
            <div key={i} className="flex items-start gap-3 bg-white border border-stone-200 rounded-xl px-4 py-3.5 hover:border-orange-200 hover:shadow-sm transition-all">
              <span className="text-lg lg:text-xl shrink-0">{s.icon}</span>
              <p className="text-xs lg:text-sm text-stone-600 leading-relaxed flex-1">{s.text}</p>
              <button className="text-xs font-semibold text-orange-600 hover:text-orange-700 shrink-0 whitespace-nowrap">Apply →</button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
